apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: jjj
spec:
  type: NodePort
  selector:
    app: jenkins
  ports:
    - port: 8080
      name: jenkins
      targetPort: 8080
      nodePort: 30002
